### ISSUE TITLE
javadoc generation failed

### ISSUE THREAD

**Issue by Tushar1729-k** [mnlipp/jdrupes-mdoclet#13]
```
<=========----> 75% EXECUTING [590ms]
> :app:javadoc
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/javadoc/DocErrorReporter
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at jdk.javadoc/jdk.javadoc.internal.tool.Start.loadDocletClass(Start.java:781)
        at jdk.javadoc/jdk.javadoc.internal.tool.Start.preprocess(Start.java:752)
        at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:371)
        at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:342)
        at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
        at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
Caused by: java.lang.ClassNotFoundException: com.sun.javadoc.DocErrorReporter
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 16 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:javadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/Users/tkohli/leetcode/ARRAY_AND_STRING/introduction_to_string/app/build/tmp/javadoc/javadoc.options'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

> Task :app:javadoc FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3/userguide/command_line_interface.html#sec:command_line_warnings
2 actionable tasks: 1 executed, 1 up-to-date
Could not execute build using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-7.3-bin.zip'.
 *  The terminal process terminated with exit code: 1. 

```

**Comment by Tushar1729-k** [comment]
I'm using jdk 17 `/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home`

**Comment by Tushar1729-k** [comment]
Here's my `build.gradle`
```
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id 'application'
    id "org.jdrupes.mdoclet" version "1.0.10"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

configurations {
    markdownDoclet
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation 'org.junit.jupiter:junit-jupiter:5.7.2'

    // This dependency is used by the application.
    implementation 'com.google.guava:guava:30.1.1-jre'
    markdownDoclet "org.jdrupes.mdoclet:doclet:3.0.0"
}

application {
    // Define the main class for the application.
    mainClass = 'introduction_to_string.App'
}

task java11doc(type: JavaExec) {
    enabled = JavaVersion.current() == JavaVersion.VERSION_17
    
    dependsOn classes
    inputs.file "overview.md"

    jvmArgs = ['--add-exports=jdk.javadoc/jdk.javadoc.internal.tool=ALL-UNNAMED',
        '--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED']
    classpath sourceSets.main.compileClasspath
    main = 'jdk.javadoc.internal.tool.Main'
    args = ['-doctitle', "My Code",
        '-overview', "overview.md",
        '-use',
        '-linksource',
        '-link', 'https://docs.oracle.com/en/java/javase/11/docs/api/',
        '--add-exports', 'jdk.javadoc/jdk.javadoc.internal.tool=ALL-UNNAMED',
        '--add-exports', 'jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED',
        '-doclet', 'org.jdrupes.mdoclet.MDoclet',
        '-docletpath', configurations.markdownDoclet.files.asType(List).join(":"),
        '-d', file("${project.buildDir}/javadoc"),
        // Specify sources to be processed
        "App.java",
        ]
}

tasks.named('test') {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
```

**Comment by mnlipp** [comment]
Please read the Readme. You need mdoclet version 3.0.0 for use with Java 17.

**Comment by Tushar1729-k** [comment]
Thanks @mnlipp ! The issue actually was I was running the `gradle javadoc` task instead of `gradle java11docs`! I suggest u make this more clear on ur README. Since that's the name of the task on the build.gradle file on ur overview.me. Granted I was a TOTAL newbie to gradle LOL but I appreciate ur documentation n markdown cuz I got it workin!
