### ISSUE TITLE
Incompatible with Gradle 6

### ISSUE THREAD

**Issue by nedtwigg** [mnlipp/jdrupes-mdoclet#3]
This line https://github.com/mnlipp/jdrupes-mdoclet/blob/50f4adc78570193f134e82c0c1dc6be09f39541b/integrations/gradle-plugin/src/org/jdrupes/mdoclet/integrations/gradle/MDocletPlugin.groovy#L44 is triggering this warning in Gradle 5.6:

```
The configuration :plugin-maven:org.jdrupes.mdoclet was resolved without accessing the project in a safe manner.  This may happen when a configuration is resolved from a thread not managed by Gradle or from a different project.  See https://docs.gradle.org/5.6/userguide/troubleshooting_dependency_resolution.html#sub:configuration_resolution_constraints for more details. This behaviour has been deprecated and is scheduled to be removed in Gradle 6.0.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:566)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$2300(DefaultConfiguration.java:139)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getSelectedArtifacts(DefaultConfiguration.java:1241)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:1230)
...
```

You can reproduce with `./gradlew jar` https://github.com/diffplug/spotless @ tag `gradle/3.24.2`

**Comment by nedtwigg** [comment]
This is surprising to me, so I've asked for help on the gradle forum as well: https://discuss.gradle.org/t/configuration-was-resolved-without-accessing-the-project-in-a-safe-manner-but-theres-no-cross-project-access/33264

**Comment by nedtwigg** [comment]
This was a dup of #4

**Comment by mnlipp** [comment]
Actually, #4 is the dup. But as it has tracked down the cause, it "wins".
